name: ensemble
channels:
  - licit-lab
  - conda-forge
dependencies:
  - python=3.9
  - numpy>=1.16
  - lxml>=4.3.3
  - xmltodict>=0.12
  - networkx>=2.5
  - matplotlib>=3.0.0
  - sqlalchemy>=1.3.5
  - pandas>=1.0.0
  - numba>=0.53
  - scipy>=1.4.1
  - click>=8.0
  - python-decouple>=3.3
  - pytest
  - coverage
  - ipython
  - ipykernel
  - symuvia=1.0.0
  - symupy=0.5.0
  - pandoc
  - sphinx
  - recommonmark
  - nbsphinx
  - sphinx-book-theme
  - pip
  - pytest
  - bump2version
  - black
  - tox
  - coverage
  - pylint
